
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN RPAREN INTEGER NEGATE PLUS EQUALS THEN WHILE LET VAR SCAN ELSE PRINT IFEXP : INTEGEREXP : SCANEXP : NEGATE EXPEXP : PLUS EXP EXPEXP : VAREXP : LPAREN EXP RPARENEXP : LPAREN LET LPAREN VAR EXP RPAREN EXP RPARENEXP : PRINT EXP'
    
_lr_action_items = {'RPAREN':([2,4,8,10,11,13,15,16,18,20,21,],[-2,-5,-1,15,-8,-3,-6,-4,19,21,-7,]),'SCAN':([0,1,2,3,4,5,7,8,11,12,13,15,16,17,19,21,],[2,2,-2,2,-5,2,2,-1,-8,2,-3,-6,-4,2,2,-7,]),'NEGATE':([0,1,2,3,4,5,7,8,11,12,13,15,16,17,19,21,],[7,7,-2,7,-5,7,7,-1,-8,7,-3,-6,-4,7,7,-7,]),'LET':([1,],[9,]),'VAR':([0,1,2,3,4,5,7,8,11,12,13,14,15,16,17,19,21,],[4,4,-2,4,-5,4,4,-1,-8,4,-3,17,-6,-4,4,4,-7,]),'PLUS':([0,1,2,3,4,5,7,8,11,12,13,15,16,17,19,21,],[5,5,-2,5,-5,5,5,-1,-8,5,-3,-6,-4,5,5,-7,]),'LPAREN':([0,1,2,3,4,5,7,8,9,11,12,13,15,16,17,19,21,],[1,1,-2,1,-5,1,1,-1,14,-8,1,-3,-6,-4,1,1,-7,]),'PRINT':([0,1,2,3,4,5,7,8,11,12,13,15,16,17,19,21,],[3,3,-2,3,-5,3,3,-1,-8,3,-3,-6,-4,3,3,-7,]),'INTEGER':([0,1,2,3,4,5,7,8,11,12,13,15,16,17,19,21,],[8,8,-2,8,-5,8,8,-1,-8,8,-3,-6,-4,8,8,-7,]),'$end':([2,4,6,8,11,13,15,16,21,],[-2,-5,0,-1,-8,-3,-6,-4,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'EXP':([0,1,3,5,7,12,17,19,],[6,10,11,12,13,16,18,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> EXP","S'",1,None,None,None),
  ('EXP -> INTEGER','EXP',1,'p_ints','r0parser.py',10),
  ('EXP -> SCAN','EXP',1,'p_scan','r0parser.py',14),
  ('EXP -> NEGATE EXP','EXP',2,'p_neg','r0parser.py',18),
  ('EXP -> PLUS EXP EXP','EXP',3,'p_add','r0parser.py',28),
  ('EXP -> VAR','EXP',1,'p_var','r0parser.py',38),
  ('EXP -> LPAREN EXP RPAREN','EXP',3,'p_parens','r0parser.py',45),
  ('EXP -> LPAREN LET LPAREN VAR EXP RPAREN EXP RPAREN','EXP',8,'p_let','r0parser.py',49),
  ('EXP -> PRINT EXP','EXP',2,'p_print','r0parser.py',55),
]
