
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NEXTBIT PREVBIT PLUS MINUS DOT COMMA EXIT GETIC COPY JUMPFWD JUMPBACKexp : GETICexp : EXIT'
    
_lr_action_items = {'GETIC':([0,],[1,]),'EXIT':([0,],[2,]),'$end':([1,2,3,],[-1,-2,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> GETIC','exp',1,'p_GETIC','dummyparser.py',14),
  ('exp -> EXIT','exp',1,'p_exit','dummyparser.py',72),
]
